---
- name: Ajout du depot PostgreSQL
  become: yes
  ansible.builtin.dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    disable_gpg_check: true
    state: present

- name: Desactivation du module postgresql natif
  become: yes
  shell:
    cmd: dnf -qy module disable postgresql

- name: Installation du paquet Postgresql 15 postgresql15-server
  become: yes
  ansible.builtin.dnf:
    name: postgresql15-server
    state: present

- name: Init de la base de donnees
  become: yes
  shell:
    cmd: /usr/pgsql-15/bin/postgresql-15-setup initdb
  ignore_errors: True

- name: Activer le service postgresql-15
  become: yes
  ansible.builtin.service:
    name: postgresql-15
    state: restarted
    enabled: true
