---
- name: Desactivation selinux
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Desactiver le service firewalld
  become: yes
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false

- name: Unconditionally reboot the machine with all defaults
  become: yes
  ansible.builtin.reboot:
